[package]
name = "mtl"
version = "0.1.3"
authors = ["andelf <andelf@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/andelf/rust-mtl"
description = "Matrix template library. Dense2D matrix, SparseMatrix."

[dependencies]
num = "*"
rand = "*"
