[package]
name = "mtl"
version = "0.1.5"
authors = ["andelf <andelf@gmail.com>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/andelf/rust-mtl"
description = "Matrix template library. Dense2D matrix, SparseMatrix."

[dependencies]
num = "0.1"
rand = "0.3"
